library(iccat.pub.data)
library(colorspace)
library(RColorBrewer)

### Gear groups
REF_GEAR_GROUPS_COLORS =
  data.table(
    GEAR_GROUP_CODE = REF_GEAR_GROUPS$CODE,
    FILL            = NA_character_
  )

REF_GEAR_GROUPS_COLORS[!GEAR_GROUP_CODE %in% c("UN", "OT"), FILL := colorRampPalette(brewer.pal(n = 12, name = "Paired"))(length(REF_GEAR_GROUPS$CODE) - 2)]
REF_GEAR_GROUPS_COLORS[GEAR_GROUP_CODE == "UN", FILL := "#888888"]
REF_GEAR_GROUPS_COLORS[GEAR_GROUP_CODE == "OT", FILL := "#222222"]

REF_GEAR_GROUPS_COLORS$GEAR_GROUP_CODE =
  factor(
    REF_GEAR_GROUPS_COLORS$GEAR_GROUP_CODE,
    labels = REF_GEAR_GROUPS$CODE,
    levels = REF_GEAR_GROUPS$CODE,
    ordered = TRUE
  )

REF_GEAR_GROUPS_COLORS[, COLOR := darken(FILL, amount = .3)]
REF_GEAR_GROUPS_COLORS = REF_GEAR_GROUPS_COLORS[order(GEAR_GROUP_CODE)]

usethis::use_data(REF_GEAR_GROUPS_COLORS, overwrite = TRUE, compress = "gzip")

### Species gear groups

REF_SPECIES_GEAR_GROUPS_ =
  REF_SPECIES_GEAR_GROUPS[, .(SPECIES_GEAR_GROUP_ORDER = max(SPECIES_GEAR_GROUP_ORDER)),
                          keyby = . (SPECIES_GEAR_GROUP)][order(SPECIES_GEAR_GROUP_ORDER)]

REF_SPECIES_GEAR_GROUPS_ =
  rbind(REF_SPECIES_GEAR_GROUPS_,
        data.table(SPECIES_GEAR_GROUP       = "Others",
                   SPECIES_GEAR_GROUP_ORDER = 99
        )
  )

REF_SPECIES_GEAR_GROUPS_COLORS =
  data.table(
    SPECIES_GEAR_GROUP = REF_SPECIES_GEAR_GROUPS_$SPECIES_GEAR_GROUP,
    FILL               = NA_character_
  )

REF_SPECIES_GEAR_GROUPS_COLORS[SPECIES_GEAR_GROUP == "All gears", FILL := "#888888"]
REF_SPECIES_GEAR_GROUPS_COLORS[SPECIES_GEAR_GROUP == "Others",    FILL := "#222222"]

REF_SPECIES_GEAR_GROUPS_COLORS[SPECIES_GEAR_GROUP == "Longline",      FILL := REF_GEAR_GROUPS_COLORS[GEAR_GROUP_CODE == "LL"]$FILL]
REF_SPECIES_GEAR_GROUPS_COLORS[SPECIES_GEAR_GROUP == "Purse seine",   FILL := REF_GEAR_GROUPS_COLORS[GEAR_GROUP_CODE == "PS"]$FILL]
REF_SPECIES_GEAR_GROUPS_COLORS[SPECIES_GEAR_GROUP == "Bait boat",     FILL := REF_GEAR_GROUPS_COLORS[GEAR_GROUP_CODE == "BB"]$FILL]
REF_SPECIES_GEAR_GROUPS_COLORS[SPECIES_GEAR_GROUP == "Sport (HL+RR)", FILL := REF_GEAR_GROUPS_COLORS[GEAR_GROUP_CODE == "HL"]$FILL]

REF_SPECIES_GEAR_GROUPS_COLORS[SPECIES_GEAR_GROUP == "Traps",         FILL := REF_GEAR_GROUPS_COLORS[GEAR_GROUP_CODE == "TP"]$FILL]
REF_SPECIES_GEAR_GROUPS_COLORS[SPECIES_GEAR_GROUP == "Trawl",         FILL := REF_GEAR_GROUPS_COLORS[GEAR_GROUP_CODE == "TW"]$FILL]
REF_SPECIES_GEAR_GROUPS_COLORS[SPECIES_GEAR_GROUP == "Troll",         FILL := REF_GEAR_GROUPS_COLORS[GEAR_GROUP_CODE == "TR"]$FILL]
REF_SPECIES_GEAR_GROUPS_COLORS[SPECIES_GEAR_GROUP == "Other surf.",   FILL := REF_GEAR_GROUPS_COLORS[GEAR_GROUP_CODE == "GN"]$FILL]

REF_SPECIES_GEAR_GROUPS_COLORS$SPECIES_GEAR_GROUP =
  factor(
    REF_SPECIES_GEAR_GROUPS_COLORS$SPECIES_GEAR_GROUP,
    labels = REF_SPECIES_GEAR_GROUPS_$SPECIES_GEAR_GROUP,
    levels = REF_SPECIES_GEAR_GROUPS_$SPECIES_GEAR_GROUP,
    ordered = TRUE
  )

REF_SPECIES_GEAR_GROUPS_COLORS[, COLOR := darken(FILL, amount = .3)]
REF_SPECIES_GEAR_GROUPS_COLORS = REF_SPECIES_GEAR_GROUPS_COLORS[order(SPECIES_GEAR_GROUP)]

usethis::use_data(REF_SPECIES_GEAR_GROUPS_COLORS, overwrite = TRUE, compress = "gzip")

### Catch types
REF_CATCH_TYPES_COLORS = brewer.pal(n = 8, name = "Set2")
REF_CATCH_TYPES_COLORS = colorRampPalette(REF_CATCH_TYPES_COLORS)(length(REF_CATCH_TYPES$CODE))

REF_CATCH_TYPES_COLORS =
  data.table(
    CATCH_TYPE_CODE = REF_CATCH_TYPES$CODE,
    FILL            = REF_CATCH_TYPES_COLORS[1:nrow(REF_CATCH_TYPES)]
  )

REF_CATCH_TYPES_COLORS$CATCH_TYPE_CODE =
  factor(
    REF_CATCH_TYPES_COLORS$CATCH_TYPE_CODE,
    labels = REF_CATCH_TYPES$CODE,
    levels = REF_CATCH_TYPES$CODE,
    ordered = TRUE
  )

REF_CATCH_TYPES_COLORS[, COLOR := darken(FILL, amount = .3)]
REF_CATCH_TYPES_COLORS = REF_CATCH_TYPES_COLORS[order(CATCH_TYPE_CODE)]

usethis::use_data(REF_CATCH_TYPES_COLORS, overwrite = TRUE, compress = "gzip")
